language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "iojs-v1"
  - "iojs-v2"
  - "iojs-v3"
  - "4"
  - "5"
  - "6"
  - "7"
env:
  - SUITE=smoke
  - SUITE=unit
  - SUITE=integration
  - SUITE=lint
  - SUITE=prerelease
  - SUITE=security
addons:
  postgresql: "9.3"
services:
  - memcached
  - mysql
  - redis
  - cassandra
  - postgresql
cache:
  apt: true
  directories:
  - $HOME/.npm
before_install:
  - ./bin/travis-setup.sh
  - make update_npm_global
install: if [ "$SUITE" != "smoke" ]; then make node_modules; fi
script: make $SUITE
matrix:
  exclude:
    - node_js: "0.8"
      env: SUITE=security
    - node_js: "0.10"
      env: SUITE=security
  allow_failures:
    - node_js: "iojs-v1"
    - node_js: "iojs-v2"
    - node_js: "iojs-v3"
    - env: SUITE=prerelease
