blank_issues_enabled: false
contact_links:
  - name: Troubleshooting
    url:  https://github.com/newrelic/node-newrelic/blob/main/README.md#support
    about: Check out the README for troubleshooting directions
