blank_issues_enabled: false
contact_links:
  - name: Troubleshooting
    url:  https://github.com/newrelic/newrelic-node-apollo-server-plugin/blob/main/README.md#support
    about: Check out the README for troubleshooting directions
