name: Notify Unreleased PRs
on:
  workflow_dispatch:
  schedule:
    # Runs on Mondays at 8AM PST (15 UTC)
    - cron: '0 15 * * 1'

jobs:
  checking-pending-prs:
    uses: newrelic/node-newrelic/.github/workflows/unreleased-prs.yaml@abstract-release-notification
    with:
      repo: node-newrelic
