on:
  workflow_dispatch:
  push:
    branches:
      - main
name: Release Please Workflow
jobs:
  release-please:
    permissions:
      contents: write # to create release commit (google-github-actions/release-please-action)
      pull-requests: write # to create release PR (google-github-actions/release-please-action)

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
            release-type: node
            changelog-path: NEWS.md
            changelog-types: |
              [
                {"type":"feat","section":"Features"},
                {"type":"fix","section":"Bug Fixes"},
                {"type":"security","section":"Security fixes"}
              ]
      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
        if: ${{ steps.release.outputs.release_created }}
      - name: Install Dependencies
        run: npm ci
        if: ${{ steps.release.outputs.release_created }}
      - name: Add RELEASE_TAG environment variable
        run: echo "RELEASE_TAG=${{ steps.release.outputs.tag_name }}" >> $GITHUB_ENV
        if: ${{ steps.release.outputs.release_created }}
      - name: Update GH Release with Support Statement
        run: node ./bin/add-support-statement.js'
        if: ${{ steps.release.outputs.release_created }}
        env:
          RELEASE_REPO: node-newrelic
          RELEASE_ORG: newrelic
      - name: Publish to Npm
        run: npm publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}