name: Server Smoke Tests

on:
    # Run on pushes to any branch. Not triggered for forked repo PRs.
  push:
  schedule:
    # Run once a day at 9AM PDT (16 UTC) on week days (1-5).
    # Last commit on default branch.
    # https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule
    - cron:  '0 16 * * 1-5'
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Run Smoke Tests
      run: npm run smoke
      env:
        TEST_LICENSE: ${{ secrets.TEST_LICENSE }}
        LASP_LICENSE: ${{ secrets.LASP_LICENSE }}
        LASP_SECURE_LICENSE: ${{ secrets.LASP_SECURE_LICENSE }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

