name: Run Specific Versioned Tests

# Manual trigger only
on:
  workflow_dispatch:
    inputs:
      test_path:
        description: 'Path to the test directory under `test/versioned/`.'
        required: true
      branch:
        description: 'The branch to test against.'
        required: true

jobs:
  versioned:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
      ref: ${{ github.event.inputs.branch }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Run Docker Services
      run: npm run services
    - name: Run Versioned Tests (npm v6 / Node 12/14)
      if: ${{ matrix.node-version == '14.x'}}
      run: npm run versioned:npm6 -- ${{ github.event.inputs.test_path }}
      env:
        VERSIONED_MODE: ${{ github.ref == 'refs/heads/main' && '--minor' || '--major' }}
    - name: Run Versioned Tests (npm v7 / Node 16+)
      if: ${{ matrix.node-version =! '14.x' }}
      run: npm run versioned:npm7 -- ${{ github.event.inputs.test_path }}
      env:
        VERSIONED_MODE: ${{ github.ref == 'refs/heads/main' && '--minor' || '--major' }}
